nelmio_cors:
    defaults:
        origin_regex: false
        allow_credentials: false
        allow_origin: ['http://localhost:4200']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        allow_methods: ['GET', 'POST','PUT','DELETE', 'PATH', 'OPTIONS']
        max_age: 3600
    paths:
        '^/contact':
            allow_origin: ['http://localhost:4200']
            allow_methods: ['POST', 'OPTIONS']
            allow_headers: ['Content-Type']
            max_age: 3600